# Understanding Faiss

In [2]:
# #Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 4.8 MB/s eta 0:00:00a 0:00:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.3/64.3 MB 5.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 6.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 6.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 6.5 MB/s eta 0:00:00a 0:00:01
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12


In [4]:
# import pandas 
import pandas as pd 

In [18]:
df = pd.read_csv("FAISS_text.csv")

In [20]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [24]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

In [26]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [28]:
vectors

array([[-0.0024739 ,  0.03626722, -0.05290461, ..., -0.0915236 ,
        -0.03970003, -0.04330488],
       [-0.03357266,  0.00980518, -0.03250131, ..., -0.05165475,
         0.02245891, -0.03156183],
       [-0.01865325, -0.04051302, -0.01235392, ...,  0.00610584,
        -0.07179646,  0.02773845],
       ...,
       [-0.0006646 ,  0.04252126, -0.05645508, ...,  0.01315469,
        -0.03183556, -0.04357661],
       [-0.03317147,  0.03252461, -0.02484839, ...,  0.01174418,
         0.05747125,  0.00571025],
       [-0.00166396,  0.00413834, -0.0459708 , ...,  0.02008529,
         0.0565625 , -0.00161594]], dtype=float32)

In [30]:
vectors.shape

(8, 768)

In [32]:
vectors[0]

array([-2.47389986e-03,  3.62672210e-02, -5.29046133e-02, -2.17348114e-02,
        1.41724003e-02, -1.01591449e-03,  2.23637111e-02,  3.65196429e-02,
        3.80901732e-02,  5.22018038e-03, -3.00865434e-02,  2.05448503e-03,
        1.08502833e-02, -8.49088356e-02, -5.57263615e-03, -6.06597625e-02,
        2.32009520e-03, -1.51408575e-02,  1.20671950e-02,  1.98904797e-02,
       -1.27936089e-02, -2.72811819e-02, -3.31878811e-02,  3.40645388e-03,
        8.41165986e-03, -1.94854047e-02,  4.88132425e-02,  2.24119276e-02,
        4.53466810e-02, -5.90892620e-02, -9.13183242e-02, -1.22331374e-03,
       -4.05046605e-02,  8.67178198e-03,  1.26565283e-06, -1.92451589e-02,
       -3.20659205e-02, -4.08172384e-02,  8.79177228e-02, -1.52631858e-02,
        1.09909289e-02, -4.47978079e-02, -4.74825967e-03,  3.52632329e-02,
        1.31071508e-02,  1.09944530e-02, -3.45765380e-03,  9.12349597e-02,
        5.68809249e-02,  4.82893363e-02, -4.51439852e-03,  3.58451419e-02,
       -2.44209319e-02, -

In [34]:
dim = vectors.shape[1]

In [36]:
dim

768

In [38]:
import faiss
index = faiss.IndexFlatL2(dim)

In [40]:
index


<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x16da77cf0> >

In [42]:
index.add(vectors)

In [44]:
search_query = "An apple a day keeps doctor away"

In [46]:
vec = encoder.encode(search_query)

In [47]:
vec.shape

(768,)

In [54]:
import numpy as np 
svec = np.array(vec).reshape(1,-1) #2D array

In [56]:
svec.shape

(1, 768)

In [58]:
index.search(svec, k=2) #k is how many similar vectors you are looking for

(array([[1.3908098, 1.7193401]], dtype=float32), array([[1, 0]]))

In [60]:
dis, I = index.search(svec, k=2)

In [62]:
dis

array([[1.3908098, 1.7193401]], dtype=float32)

In [64]:
I

array([[1, 0]])

In [66]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health